name: Build images
run-name: "Build images ${{ github.event.inputs.repository }} ${{ github.event.inputs.ref }}"

on:
  workflow_dispatch:
    inputs:
      platforms_override:
        type: string
        description: Platform override (ex linux/amd64,linux/arm64,linux/s390x,linux/ppc64le)
      platforms:
        type: string
        description: JSON encoded platforms (ex ["linux/amd64","linux/arm64","linux/s390x","linux/ppc64le"])
        default: '["linux/amd64","linux/arm64","linux/s390x","linux/ppc64le"]'
      repository:
        type: string
        default: osscontainertools/kaniko
        description: Repository to build from
      ref:
        type: string
        description: Reference to build (branch, tag, sha) [semver must start with v]
      verbose_publish:
        type: boolean
        default: false
        description: enable verbosity at publish stage

permissions: {}

jobs:
  build-images:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - executor
          - executor-debug
          - executor-slim
          - warmer

        platforms: ${{ fromJson(github.event.inputs.platforms) }}

        include:
          - image: executor
            target: kaniko-executor
            image-name: executor
            tag-suffix: ""
            release-tag: latest

          - image: executor-debug
            target: kaniko-debug
            image-name: executor
            tag-suffix: "-debug"
            release-tag: debug

          - image: executor-slim
            target: kaniko-slim
            image-name: executor
            tag-suffix: "-slim"
            release-tag: slim

          - image: warmer
            target: kaniko-warmer
            image-name: warmer
            tag-suffix: ""
            release-tag: latest

    outputs:
      san-origin-repo: ${{ steps.vars.outputs.san-origin-repo }}
      origin-repo: ${{ github.event.inputs.repository }}
      tag-base: ${{ steps.vars.outputs.tag-base }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - id: platforms
        env:
          INPUT_PLATFORMS: ${{ github.event.inputs.platforms_override }}
        run: |
          event="${{ github.event_name }}"
          PLATFORM=""
          if [[ "$event" == "pull_request" ]]; then
            PLATFORM=linux/amd64
          else
            PLATFORM="${{ matrix.platforms }}"
          fi
          if [[ -n "$INPUT_PLATFORMS" ]]; then
            echo "use overridden platform ($INPUT_PLATFORMS)"
            PLATFORM=$INPUT_PLATFORMS
          fi
          echo "platforms=$PLATFORM" | tee -a $GITHUB_OUTPUT
          echo "san-platforms=${PLATFORM/\//-}" | tee -a $GITHUB_OUTPUT

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.inputs.ref }}
          repository: ${{ github.event.inputs.repository }}

      - name: setup vars
        id: vars
        env:
          REF: ${{ github.event.inputs.ref }}
        run: |

          # if ref is a semver, tag-base is the ref
          # else tag-base is ref-shortsha

          # REF is a semver
          if [[ -n "$(echo $REF | grep -iE '^v[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9.-]+)?$')" ]]; then
            SEMVER_CORE="${REF#v}"
            SEMVER_CORE="${SEMVER_CORE%%-*}"
            SPLIT_VERSION=( ${SEMVER_CORE//./ } )
            SEMVER_MAJOR="${SPLIT_VERSION[0]}"
            SEMVER_MINOR="${SPLIT_VERSION[1]}"
            SEMVER_PATCH="${SPLIT_VERSION[2]}"

            sed -r \
              -e "0,/^VERSION_MAJOR \?=/ s,^VERSION_MAJOR \?=.+$,VERSION_MAJOR ?= ${SPLIT_VERSION[0]}," \
              -e "0,/^VERSION_MINOR \?=/ s,^VERSION_MINOR \?=.+$,VERSION_MINOR ?= ${SPLIT_VERSION[1]}," \
              -e "0,/^VERSION_BUILD \?=/ s,^VERSION_BUILD \?=.+$,VERSION_BUILD ?= ${SPLIT_VERSION[2]}," \
              -i Makefile

            echo tag-base="$REF" >> $GITHUB_OUTPUT
          else
            echo tag-base="$REF-$(git rev-parse --short HEAD 2>/dev/null)" >> $GITHUB_OUTPUT
          fi
          echo "ref=$REF" >> $GITHUB_OUTPUT
          SANITIZED_ORIGIN_REPO=$(echo -n ${{ github.event.inputs.repository }} | tr -c a-z - )
          echo image-base=ghcr.io/${{ github.repository_owner }}/dist/"${SANITIZED_ORIGIN_REPO}"/ >> $GITHUB_OUTPUT
          echo san-origin-repo=$SANITIZED_ORIGIN_REPO >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          platforms: ${{ steps.platforms.outputs.platforms }}

      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: build
        with:
          context: .
          file: ./deploy/Dockerfile
          platforms: ${{ steps.platforms.outputs.platforms }}
          push: true
          provenance: false
          outputs: type=docker,dest=${{ runner.temp }}/${{ steps.vars.outputs.san-origin-repo }}=${{ matrix.image-name }}=${{ steps.vars.outputs.tag-base }}${{ matrix.tag-suffix }}=${{ steps.platforms.outputs.san-platforms }}.tar
          tags: ${{ steps.vars.outputs.image-base }}${{ matrix.image-name }}:${{ steps.vars.outputs.tag-base }}${{ matrix.tag-suffix }}-${{ steps.platforms.outputs.san-platforms }}
          no-cache-filters: certs
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.san-origin-repo }}=${{ steps.vars.outputs.tag-base }}=${{ matrix.image-name }}=${{ steps.vars.outputs.tag-base }}${{ matrix.tag-suffix }}=${{ steps.platforms.outputs.san-platforms }}
          path: ${{ runner.temp }}/${{ steps.vars.outputs.san-origin-repo }}=${{ matrix.image-name }}=${{ steps.vars.outputs.tag-base }}${{ matrix.tag-suffix }}=${{ steps.platforms.outputs.san-platforms }}.tar

  publish-images:
    name: "Publish all at once"
    needs: build-images

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build-images.outputs.san-origin-repo }}=${{ needs.build-images.outputs.tag-base }}=*
          merge-multiple: true
          path: ${{ runner.temp }}

      - name: Load images
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DOCKER_FLAGS=""
          [ "${{ github.event.inputs.verbose_publish }}" = "true" ] && set -x && DOCKER_FLAGS="-D"
          for IMAGE_TAR in ${{ runner.temp }}/${{ needs.build-images.outputs.san-origin-repo }}=*.tar; do
            docker load --input ${IMAGE_TAR}
          done

          docker image ls -a

          PLATFORMS="$(echo '${{ github.event.inputs.platforms }}' | jq -r '.[]')"

          for IMAGE_BASE in \
              ghcr.io/${{ github.repository_owner }}/dist/${{ needs.build-images.outputs.san-origin-repo }}/executor:${{ needs.build-images.outputs.tag-base }} \
              ghcr.io/${{ github.repository_owner }}/dist/${{ needs.build-images.outputs.san-origin-repo }}/executor:${{ needs.build-images.outputs.tag-base }}-slim \
              ghcr.io/${{ github.repository_owner }}/dist/${{ needs.build-images.outputs.san-origin-repo }}/executor:${{ needs.build-images.outputs.tag-base }}-debug \
              ghcr.io/${{ github.repository_owner }}/dist/${{ needs.build-images.outputs.san-origin-repo }}/warmer:${{ needs.build-images.outputs.tag-base }} \
              ; do

            LATEST=${IMAGE_BASE/:${{ needs.build-images.outputs.tag-base }}/:latest}
            PLATFORM_SUFFIX=()
            for PLATFORM in $PLATFORMS; do
              IFS=/ read -r OS ARCH <<< "$PLATFORM"
              PLATFORM_SUFFIX+=($IMAGE_BASE-$OS-$ARCH)
            done

            # Create main manifest
            docker $DOCKER_FLAGS manifest create $IMAGE_BASE "${PLATFORM_SUFFIX[@]}"
            docker $DOCKER_FLAGS manifest create $LATEST     "${PLATFORM_SUFFIX[@]}"

            # Annotate manifest parts
            for PLATFORM in $PLATFORMS; do
              IFS=/ read -r OS ARCH <<< "$PLATFORM"
              docker manifest annotate $IMAGE_BASE $IMAGE_BASE-$OS-$ARCH --os $OS --arch $ARCH
              docker manifest annotate $LATEST     $IMAGE_BASE-$OS-$ARCH --os $OS --arch $ARCH
            done

            # Push the result
            docker manifest push $IMAGE_BASE
            docker manifest push $LATEST

          done

          cat << EOF | gh release create "${{ needs.build-images.outputs.origin-repo }}/${{ needs.build-images.outputs.tag-base }}" \
            --notes "${{ needs.build-images.outputs.origin-repo }} ${{ needs.build-images.outputs.tag-base }}" \
            --title "${{ needs.build-images.outputs.origin-repo }} ${{ needs.build-images.outputs.tag-base }}" \
            -F - \
            ${{ runner.temp }}/${{ needs.build-images.outputs.san-origin-repo }}=*.tar

          Architecture available:
          \`\`\`
          ${PLATFORMS[@]}
          \`\`\`

          Tar archives for \`docker load --input <file>\` linked ot the release.
          Images available as artifacts:
            - **Executor**: https://github.com/${{ github.repository }}/pkgs/container/dist%2F${{ needs.build-images.outputs.san-origin-repo }}%2Fexecutor
            - **Warmer**: https://github.com/${{ github.repository }}/pkgs/container/dist%2F${{ needs.build-images.outputs.san-origin-repo }}%2Fwarmer

          Or for \`docker pull\`:
            - \`docker pull ghcr.io/${{ github.repository_owner }}/dist/${{ needs.build-images.outputs.san-origin-repo }}/executor:${{ needs.build-images.outputs.tag-base }}\`
            - \`docker pull ghcr.io/${{ github.repository_owner }}/dist/${{ needs.build-images.outputs.san-origin-repo }}/executor:${{ needs.build-images.outputs.tag-base }}-slim\`
            - \`docker pull ghcr.io/${{ github.repository_owner }}/dist/${{ needs.build-images.outputs.san-origin-repo }}/executor:${{ needs.build-images.outputs.tag-base }}-debug\`
            - \`docker pull ghcr.io/${{ github.repository_owner }}/dist/${{ needs.build-images.outputs.san-origin-repo }}/warmer:${{ needs.build-images.outputs.tag-base }}\`
          EOF

      - uses: geekyeggo/delete-artifact@v5
        with:
            name: ${{ needs.build-images.outputs.san-origin-repo }}=${{ needs.build-images.outputs.tag-base }}=*
